// File generated by FlutterFire CLI.
// JALANKAN: flutterfire configure
// File firebase_options.dart akan di-generate (ada di .gitignore)
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:xxx:web:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project',
    authDomain: 'your-project.firebaseapp.com',
    storageBucket: 'your-project.firebasestorage.app',
    measurementId: 'G-XXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:xxx:android:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project',
    storageBucket: 'your-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: '1:xxx:ios:xxx',
    messagingSenderId: 'xxx',
    projectId: 'your-project',
    storageBucket: 'your-project.firebasestorage.app',
    iosBundleId: 'id.traka.app',
  );
}
