-- Traka PostgreSQL Schema
-- Jalankan di Supabase SQL Editor atau psql

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT,
  "phoneNumber" TEXT,
  "displayName" TEXT,
  "photoUrl" TEXT,
  "driverSIMVerifiedAt" TIMESTAMPTZ,
  "driverSIMNomorHash" TEXT,
  "vehicleMerek" TEXT,
  "vehicleType" TEXT,
  "vehicleJumlahPenumpang" INT,
  role TEXT,
  region TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  "suspendedAt" TIMESTAMPTZ,
  "suspendedReason" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  "orderNumber" TEXT,
  "passengerUid" TEXT NOT NULL,
  "driverUid" TEXT NOT NULL,
  "routeJourneyNumber" TEXT NOT NULL DEFAULT '',
  "passengerName" TEXT,
  "passengerPhotoUrl" TEXT,
  "originText" TEXT NOT NULL,
  "destText" TEXT NOT NULL,
  "originLat" DOUBLE PRECISION,
  "originLng" DOUBLE PRECISION,
  "destLat" DOUBLE PRECISION,
  "destLng" DOUBLE PRECISION,
  "passengerLat" DOUBLE PRECISION,
  "passengerLng" DOUBLE PRECISION,
  "passengerLocationText" TEXT,
  status TEXT NOT NULL DEFAULT 'pending_agreement',
  "driverAgreed" BOOLEAN DEFAULT FALSE,
  "passengerAgreed" BOOLEAN DEFAULT FALSE,
  "driverCancelled" BOOLEAN DEFAULT FALSE,
  "passengerCancelled" BOOLEAN DEFAULT FALSE,
  "adminCancelled" BOOLEAN DEFAULT FALSE,
  "adminCancelledAt" TIMESTAMPTZ,
  "adminCancelReason" TEXT,
  "orderType" TEXT NOT NULL DEFAULT 'travel',
  "receiverUid" TEXT,
  "receiverName" TEXT,
  "receiverPhotoUrl" TEXT,
  "receiverAgreedAt" TIMESTAMPTZ,
  "receiverLat" DOUBLE PRECISION,
  "receiverLng" DOUBLE PRECISION,
  "receiverLocationText" TEXT,
  "receiverScannedAt" TIMESTAMPTZ,
  "jumlahKerabat" INT,
  "agreedPrice" DOUBLE PRECISION,
  "agreedPriceAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ,
  "updatedAt" TIMESTAMPTZ,
  "completedAt" TIMESTAMPTZ,
  "lastMessageAt" TIMESTAMPTZ,
  "lastMessageSenderUid" TEXT,
  "lastMessageText" TEXT,
  "driverLastReadAt" TIMESTAMPTZ,
  "chatHiddenByPassenger" BOOLEAN DEFAULT FALSE,
  "chatHiddenByDriver" BOOLEAN DEFAULT FALSE,
  "chatHiddenByReceiver" BOOLEAN DEFAULT FALSE,
  "passengerLastReadAt" TIMESTAMPTZ,
  "receiverLastReadAt" TIMESTAMPTZ,
  "passengerBarcodePayload" TEXT,
  "driverBarcodePickupPayload" TEXT,
  "driverBarcodePayload" TEXT,
  "passengerScannedPickupAt" TIMESTAMPTZ,
  "destinationValidationLevel" TEXT,
  "driverScannedAt" TIMESTAMPTZ,
  "pickupLat" DOUBLE PRECISION,
  "pickupLng" DOUBLE PRECISION,
  "passengerScannedAt" TIMESTAMPTZ,
  "dropLat" DOUBLE PRECISION,
  "dropLng" DOUBLE PRECISION,
  "tripDistanceKm" DOUBLE PRECISION,
  "ferryDistanceKm" DOUBLE PRECISION,
  "tripFareRupiah" DOUBLE PRECISION,
  "tripBarangFareRupiah" DOUBLE PRECISION,
  "scheduleId" TEXT,
  "scheduledDate" TEXT,
  "driverArrivedAtPickupAt" TIMESTAMPTZ,
  "passengerTrackDriverPaidAt" TIMESTAMPTZ,
  "passengerLacakBarangPaidAt" TIMESTAMPTZ,
  "receiverLacakBarangPaidAt" TIMESTAMPTZ,
  "autoConfirmPickup" BOOLEAN DEFAULT FALSE,
  "autoConfirmComplete" BOOLEAN DEFAULT FALSE,
  "passengerViolationFee" DOUBLE PRECISION,
  "driverViolationFee" DOUBLE PRECISION,
  "passengerRating" INT,
  "passengerReview" TEXT,
  "passengerRatedAt" TIMESTAMPTZ,
  "barangCategory" TEXT,
  "barangNama" TEXT,
  "barangBeratKg" DOUBLE PRECISION,
  "barangPanjangCm" DOUBLE PRECISION,
  "barangLebarCm" DOUBLE PRECISION,
  "barangTinggiCm" DOUBLE PRECISION,
  "passengerAppLocale" TEXT,
  "barangFotoUrl" TEXT,
  "lacakBarangIapFeeRupiah" INT
);

CREATE INDEX IF NOT EXISTS idx_orders_driver ON orders("driverUid");
CREATE INDEX IF NOT EXISTS idx_orders_passenger ON orders("passengerUid");
CREATE INDEX IF NOT EXISTS idx_orders_receiver ON orders("receiverUid");
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_route ON orders("routeJourneyNumber");
